<table border="1">
  <?php
  for($x=0; $x<$articles->count();$x++){
  ?>
    <tr >
      <tr>
        <tr>
          <td>
            <?php
              echo $date=date_format(date_create($articles[$x]->publicationDate), 'd F');
            ?>
          </td>
          <td>
            <?php
              print($articles[$x]->title);
            ?>
          </td>
        </tr>
        <tr>
          <td colspan="2">
          <?php
            print($articles[$x]->summary);
          ?>
          </td>
        </tr>
      </tr>
    </tr>
  <?php
  }
  ?>
</table>
<?php
 echo $this->tag->linkTo(
    "archive",
    "Article Archive"
);
?>
