<table border="1">
  <?php
  for($x=0; $x<$articles->count();$x++){
  ?>
    <tr >
      <tr>
        <tr>
          <td>
            <h5>
              <?php
                echo $date=date_format(date_create($articles[$x]->publicationDate), 'd F');
              ?>
            </h5>
          </td>
          <td>
            <h2>
              <a href="/article/<?php print($articles[$x]->id) ?>">
                <?php
                print($articles[$x]->title);
                ?>
              </a>
            </h2>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <h3>
              <?php
                print($articles[$x]->summary);
              ?>
            </h3>
          </td>
        </tr>
      </tr>
    </tr>
  <?php
  }
  ?>
</table>
<?php
 echo $this->tag->linkTo(
    "archive",
    "Article Archive"
);
?>
