
  <h4>Widget News Admin</h4>
  <p>
    You're logged in as admin.
    <?php echo $this->tag->linkTo(
        "signin/logout",
        "Log out  "
    );
    ?>
  </p>
  <h2> All Articles </h2>

  <TABLE BORDER="1">
  <CAPTION> Articles </CAPTION>
    <TR>
      <TH> Publication Date </TH>
      <TD> Artcile </TD>
    </TR>
  </TABLE>

<?php
$articleNumber = 5;
echo $articleNumber.($articleNumber>1 ? ' articles ' : ' article ').' in total. ';

echo $this->tag->linkTo(
    "administration",
    "Add new Article"
);
