<?php
echo Phalcon\Tag::stylesheetLink("css/bootstrap.css");
echo Phalcon\Tag::stylesheetLink("css/style.css");
?>
  <div class="title" id="articleTit">
  <h2> All Articles</h2>
  </div>
  <div class="row tableArticles" id="title">
    <div class="col-xs-3 PubDateArticles">
    Publication Date
    </div>
    <div class="col-xs-9 TitArticles">
    Article
    </div>
  </div>
<?php
for($x=0; $x<$articles->count();$x++){
?>
<div class="tableauArticles">
  <a href="/administration/edit/<?php print($articles[$x]->id) ?>" class="click">
    <div class="row tableArticles <?php echo $x%2==0? '2' : 'yellowBackTable' ?>">
    <div class="col-xs-3 PubDateArticles">
      <?php
      echo $date=date_format(date_create($articles[$x]->publicationDate), 'd M Y');
      ?>
    </div>
    <div class="col-xs-9 TitArticles">
      <?php
      print($articles[$x]->title);
      ?>
    </div>
  </div>
</a>
</div>


<?php
}
?>
<div id="endArticles">
<?php
  $articleNumber= $articles->count() ;
  echo $articleNumber.($articleNumber>1 ? ' articles ' : ' article ').' in total. </br> ';
?>
</div>
<?php
  echo $this->tag->linkTo(
  "administration",
  "Add new Article"
  );

?>
