

<?php
 echo $this->tag->form("administration/register"); ?>
    <div>
        <label for="title">Title</label>
        <?php echo $this->tag->textField(
          [
            'title',
            'placeholder' => 'Name of the Article',
          ]); ?>
    </div>

    <div>
        <label for="summary">Summary</label>
        <?php echo $this->tag->textField(
          [
            'summary',
            'placeholder' => 'Summary here',
          ]); ?>
    </div>

    <div>
        <label for="content">Content</label>
        <?php echo $this->tag->textArea(
          [
            'content',
            'placeholder' => 'Write the content here',
          ]); ?>
    </div>

    <div>
        <label for="publicationDate">Publication Date</label>
        <?php echo $this->tag->dateField("publicationDate"); ?>
    </div>

    <div>
        <?php echo $this->tag->submitButton("Register"); ?>
    </div>

</form>
