<?php

 echo $this->tag->form("signin/login"); ?>
 <h2>Sign in using this form</h2>
    <p>
        <label for="userName">Username</label>
        <?php echo $this->tag->textField("userName"); ?>
    </p>

    <p>
        <label for="userPassword">Password</label>
        <?php echo $this->tag->passwordField("userPassword"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Login"); ?>
    </p>

</form>
<?php

echo $this->tag->linkTo(
    "createUser",
    "Create User"
);
 ?>
